name: Deploy Sphinx documentation to Pages

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write  # needed to push docs to main
      pages: write
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r docs/requirements.txt

    - name: Run API auto-doc script
      run: python scripts/generate-api-reference.py

    - name: Commit generated docs
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/source/api
        git add docs/source/api/api_reference.rst
        git diff --cached --quiet || git commit -m "Auto-generate API docs"
        git push origin main

    - name: Deploy Sphinx site to GitHub Pages
      id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: docs/source
        requirements_path: docs/requirements.txt