name: Run test suites for QCrBoxAPIClient

# Controls when the workflow will run
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_robot_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout QCrBoxAPIClient
        uses: actions/checkout@v4
        with:
            path: ./QCrBoxAPIClient

      - name: Checkout QCrBox
        uses: actions/checkout@v4
        with:
            ref: dev
            path: ./QCrBox
            repository: QCrBox/QCrBox

      - name: Install Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python Poetry and UV and project dependencies
        run: |
          pip install --upgrade poetry
          pip install --upgrade uv
          cd $GITHUB_WORKSPACE/QCrBox
          uv pip install --system -r ./pyqcrbox/requirements-dev.txt
          uv pip install --system pyqcrbox@./pyqcrbox
          cd $GITHUB_WORKSPACE/QCrBoxAPIClient
          poetry install

      - name: Prepare QCrBoxAPIClient repository for adding coverage badge
        run: |
            cd $GITHUB_WORKSPACE/QCrBoxAPIClient
            git config user.name "github-actions"
            git config user.email "github-actions@github.com"
            git fetch origin main
            git checkout main
            git pull --ff-only origin main

      - name: Bring up QCrBox registry and applications
        run: |
            cd $GITHUB_WORKSPACE/QCrBox
            docker container prune -f
            docker network prune -f
            qcb up --test-only

      - name: Wait for QCrBox registry to be ready
        run: $GITHUB_WORKSPACE/QCrBoxAPIClient/.github/scripts/check_qcb_healthy.sh

      - name: Run Robot Framework test suites
        run: |
          cd $GITHUB_WORKSPACE/QCrBox
          set -a
          source .env.test
          set +a

          cd $GITHUB_WORKSPACE/QCrBoxAPIClient/robot_tests
          poetry run coverage run -m robot *.robot

      - name: Create new coverage badge and add to repository
        run: |
          cd $GITHUB_WORKSPACE/QCrBoxAPIClient/robot_tests
          poetry run coverage-badge -f -o ../coverage.svg
          git add ../coverage.svg
          git diff --cached --quiet || git commit -m "Updating test coverage badge"
          git push origin main

      - name: Clean-up QCrBox
        if: always()
        run: |
          cd $GITHUB_WORKSPACE/QCrBox
          qcb down || true
          docker container prune -f
          docker network prune -f
